#!/bin/bash
#SBATCH --partition=normal
#SBATCH --ntasks=64
#SBATCH --time=5-01:00:00
#SBATCH --job-name=130-3
mpirun ~/scratch/lammps/src/lmp_mpi -in system.run3.130000

#python notify.py $SLURM_JOB_ID
