include "system.in"
velocity	all create 1 277387 mom yes


#include "system.prepare"

variable N equal 500
variable T equal 293
variable compressionLength equal 10


neighbor	0.3 bin
neigh_modify	delay 10

thermo		100
timestep	0.002

fix nvt all nvt temp ${T} ${T} 1.0
#restart 1000 restartFiles/squeeze*.restart

dump myDump all atom 10 dumpFiles/SiO2_*.dump

#fix deform all deform 1 z delta 0 -${compressionLength} remap x



run ${N}
