

variable N equal 4000
variable T equal 500

velocity	all create ${T} 277387 mom yes
include "system.prepare"

#read_restart squeeze.1000.restart
#include "system.in.settings"
restart 1000 squeeze*.restart
neighbor	0.3 bin
neigh_modify	delay 10

thermo		100
timestep	0.002

dump myDump all atom 10 SiO2.dump

#Move the top z-boundary downwards
variable compressionLength equal 200
fix deform all deform 1 z delta 0 -${compressionLength} remap x

fix nvt all nvt temp ${T} ${T} 1.0
run ${N}
